### ISSUE TITLE
Custom improvements: reducing color-change moves, slicer-controlled purging, and Bambu Studio profile

### ISSUE THREAD

**Issue by function3d** [ghzserg/zmod_ff5x#3]
Hi,

I would like to share some custom changes and optimizations that I’ve been experimenting with. They may not be directly applicable to the project as a whole, but could be useful as inspiration or reference for other users.

**1. Reduction of unnecessary moves during color change**

   - I provide the necessary G-code in `user.cfg` below.
   - The goal is to minimize idle moves and make the color change more efficient.
   - With these adjustments, the complete color change process (including flush) is now reduced to ~45 seconds.

**2. Purge deactivation in firmware, controlled by the slicer**

   -  I provide a `filament.json` (below) where flushing is deactivated, the filament only reach the hot part of the hotend and  is ready for the slicer filament  change gcode (similar to how BambuLab printers handle filament changes).

   - Benefits:

        - Flushing volumes and multipliers are fully controlled from the slicer.

        - More accurate estimates of time and filament usage.

        - Ability to use flush into infill or flush into object, so material is reused instead of discarded as waste.

        - A 20 mm retraction before cut works without issues and makes it possible to reduce the flushing multiplier to 0.7, while still achieving perfect color changes every time.

**3. Bambu Studio profile**

   - I also created a profile for Bambu Studio (below).
   - **I find some advantages over Orca**, especially in how the prime tower is generated, which is much better managed.

**Notes**
   - **These changes have only been tested with commit 1.5: 1.5.5-57.**
   - **These changes should not be used unless you clearly understand what they involve and their possible implications.**
   - My changes are only tested with PLA.
   - Printing temperature: 205 °C for PLA, as I personally prefer a more matte finish.
   - Why 3 walls, 15% infill, print infill first? (print infill first can be problematic in bridges).

        - This setup provides a good balance between robustness and speed.
        - It also takes full advantage of flush into infill, improving part strength by incorporating material that would otherwise be discarded.
   - The filament change G-code is in the .3mf file and requires the optimizations defined in user.cfg to work properly.
   

**Conclusion:**
These changes are more of a customization, but maybe some of the ideas can be useful for the project in general, or at least for other users who want to try similar workflows.

I’m sharing them here in case they can help improve the ecosystem around the project 🚀

`mod_data/user.cfg`

```
[printer]
max_velocity: 500
max_accel: 10000
square_corner_velocity: 9

[probe]                                             
samples: 2
samples_tolerance:0.05
samples_tolerance_retries:3
lift_speed:15
sample_retract_dist:1

[bed_mesh]                         
speed: 300                         
horizontal_move_z:2  

[gcode_macro _INSERT_PRUTOK_IFS]
description: 
gcode:
    {% set temp = printer[printer.toolhead.extruder].target if printer.toolhead.extruder != '' else 0 %}

    {% set prutok                          = params.PRUTOK|default(1)|int %}
    {% set extruder_temp                   = params.TEMP|default(205)|int %}
    {% set need_stop                       = params.NEED_STOP|default(1)|int %}

    {% set filament_type                   = params.FILAMENT_TYPE|default("PLA")|string %}
    {% set filament_unload_before_cutting  = params.FILAMENT_UNLOAD_BEFORE_CUTTING|default(0)|float %}
    {% set filament_unload_after_cutting   = params.FILAMENT_UNLOAD_AFTER_CUTTING|default(5)|float %}
    {% set filament_unload_after_drop      = params.FILAMENT_UNLOAD_AFTER_DROP|default(3)|float %}
    {% set filament_unload_speed           = params.FILAMENT_UNLOAD_SPEED|default(600)|int %}
    {% set filament_load_speed             = params.FILAMENT_LOAD_SPEED|default(300)|int %}
    {% set filament_tube_length            = params.FILAMENT_TUBE_LENGTH|default(1000)|int %}
    {% set filament_drop_length            = params.FILAMENT_DROP_LENGTH|default(90)|int %}
    {% set filament_drop_length_add        = params.FILAMENT_DROP_LENGTH_ADD|default(0)|int %}
    {% set filament_fan_speed              = params.FILAMENT_FAN_SPEED|default(102)|int %}

    RESPOND PREFIX="info" MSG="Loading filament {prutok} {filament_type}"
    _G28
    #_GOTO_TRASH
    M106 S0
    
    {% set client = printer['gcode_macro _CLIENT_VARIABLE'] | default({}) %}
    
    IFS_REMOVE_CURRENT_PRUTOK TEMP={temp}

    RESPOND PREFIX="info" MSG="Heating the nozzle to {extruder_temp} degrees"
    #M104 S{extruder_temp}
    SET_HEATER_TEMPERATURE HEATER=extruder TARGET={extruder_temp}
    TEMPERATURE_WAIT SENSOR=extruder MINIMUM={extruder_temp-4}
    
    # Bloquear filamento
    IFS_F24 PRUTOK={prutok}

    # Cargar filamento
    IFS_F10 PRUTOK={prutok} LEN={filament_tube_length} SPEED={filament_unload_speed*2} CHECK=1
    
    #_SBROS_TRASH_DAVIM PRUTOK={prutok} FILAMENT_FAN_SPEED={filament_fan_speed} FILAMENT_DROP_LENGTH={filament_drop_length} FILAMENT_DROP_LENGTH_ADD={filament_drop_length_add} FILAMENT_LOAD_SPEED={filament_load_speed} FILAMENT_UNLOAD_AFTER_DROP=0
    _GOTO_TRASH
    _DISABLE_SENSOR
        G1 E{filament_drop_length} F{filament_load_speed}
        {% if prutok != 0 %}
            # Cargar filamento
            IFS_F10 PRUTOK={prutok} LEN={filament_drop_length} SPEED={filament_load_speed} SLEEP=1
            # Detener movimiento
            #IFS_F112
            # Desbloquear filamento
            IFS_F39 PRUTOK={prutok}
        {% endif %}
        M400
    _ENABLE_SENSOR
    # Marcar el filamento como insertado
    IFS_F23 PRUTOK={prutok}
    M106 S0
    {% if need_stop == 1 %}
        M104 S0 T0
    {% endif %}
    IFS_EXTRUDER_SENSOR
    {% if prutok != 0 %}
        SET_EXTRUDER_SLOT SLOT={prutok}
        SET_CURRENT_PRUTOK
    {% endif %}
    
[gcode_macro _REZGEM_PRUTOK]
description: Отрезаем пруток
gcode:
    {% set filament_unload_before_cutting  = params.FILAMENT_UNLOAD_BEFORE_CUTTING|default(0)|float %}
    {% set filament_unload_after_cutting   = params.FILAMENT_UNLOAD_AFTER_CUTTING|default(5)|float %}
    {% set filament_unload_speed           = params.FILAMENT_UNLOAD_SPEED|default(600)|float %}

    RESPOND PREFIX="info" MSG="Cutting the filament"

    G92 E0
    G90
    #_DISABLE_SENSOR #probablemente no haga falta
    # move to cut position and retract (20mm) at the same time
    G1 Y10 E-{filament_unload_before_cutting/3} F18000
    G1 Y-7.70 E-{filament_unload_before_cutting/3} F1800 
    G1 X20 E-{filament_unload_before_cutting/3} F12000
    #_ENABLE_SENSOR # probablemente no haga falta
    G1 X-2.00 F600 #Cut
    M400
    G92 E0

    #_DISABLE_SENSOR
        G1 E-{filament_unload_after_cutting} F{filament_unload_speed}
    #    M400
    #_ENABLE_SENSOR
    
    G1 F18000

[gcode_macro _GOTO_TRASH]
description: Go to trash
gcode:
    
    RESPOND PREFIX="info" MSG="Go to trash"

    G90
    {% if printer.toolhead.position.x != 52.50 %}
    G1 X52.50 F12000
    {% endif %}
    {% if printer.toolhead.position.y != 228.80 %}
        G1 Y220 F12000
        G1 Y228.80 F3000
    {% endif %}
    M400

[gcode_macro _SBROS_TRASH]
description: Сброс через какашник без выдавливания
gcode:
    G1 Y220 F12000      ; Выход из какашника
    G1 Y228.80 F3000    ; Вход в какашник
    G1 Y220 F12000      ; Выход из какашника
    G1 Y228.80 F3000    ; Вход в какашник
    G1 Y220 F12000      ; Выход из какашника
    G1 Y228.80 F3000    ; Вход в какашник
    G1 F12000

[gcode_macro _CLEAR_REZINA]
description: Чистка об резинку
gcode:
     RESPOND PREFIX="info" MSG="Cleaning the nozzle on rubber"

    G1 Y220 F3000
    G1 X65              ; 1/2 резинки по X
    G1 Y228.80          ; заезд на резинку по Y
    G1 X73              ; 1/2 резинки по X
    G1 X65              ; 1/4 резинки по X
    G1 X73              ; 1/2 резинки по X
    G1 X65              ; 1/4 резинки по X
    G1 X73              ; 1/2 резинки по X
    G1 X65              ; 1/4 резинки по X
    G1 Y220             ; выезд с резинки
    G1 F12000
    M400

[gcode_macro _PRINT_CLEAR_NOZZLE]
gcode:
    

[gcode_macro _ORIG_CLEAR_NOZZLE]
gcode:
    {% set extruder_temp = params.EXTRUDER_TEMP|default(230)|float %}
    {% set bed_temp = params.BED_TEMP|default(80)|float %}
    {% set ignore_temp = params.IGNORE_TEMP|default(0)|int %}
    {% set preclear = params.PRECLEAR|default(0)|int %}

    {% if ignore_temp == 0%}
        RESPOND PREFIX="info" MSG="Running native nozzle cleaning {extruder_temp}/{bed_temp}"
    {% else %}
        RESPOND PREFIX="info" MSG="Nozzle pre-cleaning"
    {% endif %}

    _G28
    G1 Z5 F600
    _GOTO_TRASH
    M140 S{bed_temp}        
    M104 S{extruder_temp} T0
    TEMPERATURE_WAIT SENSOR=extruder MINIMUM={extruder_temp}
    M104 S{140}
    M106 S102
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E-3 F300
    G92 E0
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={180}
    _SBROS_TRASH
    _CLEAR_REZINA
    G1 Y228.80 F3000
    M106 S{255/100*80}
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={142}
    M106 S0

[gcode_macro KAMP]
description: Adaptive bed
gcode:
    {% set extruder_temp = params.EXTRUDER_TEMP|default(240)|float %}
    {% set bed_temp = params.BED_TEMP|default(80)|float %}

    BED_MESH_CLEAR          ; Очистка профиля стола
    M400

    _ORIG_CLEAR_NOZZLE EXTRUDER_TEMP={extruder_temp} BED_TEMP={bed_temp}

    _KAMP_BED_MESH_CALIBRATE

    #_GOTO_TRASH

    M140 S{bed_temp}
    M104 S{extruder_temp}
    TEMPERATURE_WAIT SENSOR=heater_bed MINIMUM={bed_temp-2}
    TEMPERATURE_WAIT SENSOR=extruder MINIMUM={extruder_temp-4}

```

`mod_data/filament.json`
```
{
	"PLA": {
		"temp": 205,
		"filament_unload_before_cutting": 20,
		"filament_unload_after_cutting": 5,
		"filament_unload_after_drop": 0.1,
		"filament_load_speed":300,
		"filament_unload_speed": 600,
		"filament_tube_length": 1000,
		"filament_drop_length": 32.7,
		"filament_drop_length_add": 90,
		"nozzle_cleaning_length": 55,
		"filament_fan_speed": 102,
		"filament_autoinsert_empty_length": 600,
		"filament_autoinsert_full_length": 550,
		"filament_autoinsert_ret_length": 90,
		"filament_autoinsert_speed": 1200
	},
....
```
`Bambu Studio 3mf`
[PANDA_AD5X_BS.zip](https://github.com/user-attachments/files/22135680/PANDA_AD5X_BS.zip)

**Comment by ghzserg** [comment]
Thanks for the work done.
The changes are interesting.

But I would suggest comparing them with the current version, since quite a few things have been fixed in it. In particular, working without IFS when prutok = 0

And you use the dangerous _GOTO_TRASH
The point is that you can only enter the basket from Y220 and at X 52.50.

If the nozzle for some reason remains at Y228, and at X, for example, 78, then calling _GOTO_TRASH in your version will lead to entering the basket and hitting the pedal.

```
[gcode_macro _GOTO_TRASH]
description: Go to trash
gcode:
    
    RESPOND PREFIX="info" MSG="Go to trash"

    G90
    {% if printer.toolhead.position.x != 52.50 %}
    G1 X52.50 F12000
    {% endif %}
    {% if printer.toolhead.position.y != 228.80 %}
        G1 Y220 F12000
        G1 Y228.80 F3000
    {% endif %}
    M400
```

```
[gcode_macro _GOTO_TRASH]
description: Go to trash
gcode:
    {% set not220 = params.NOT220|default(0) %}

    RESPOND PREFIX="info" MSG="Go to trash"

    G90
    {% if printer.toolhead.position.x != 52.50 %}
        {% if printer.toolhead.position.y > 220.00 %}
            G1 Y220 F12000
            M400
        {% endif %}
        G1 X52.50 F12000
        M400
    {% endif %}
    {% if not220 == 0 %}
        G1 Y220 F12000
    {% endif %}
    G1 Y228.80 F3000
    M400
```

I really like that you are helping the project.

And I would suggest to add useful things to the general code of the project with the discussion with you.

I suggest to start with KAMP, as with the simplest
In your version, smart parking is removed. As a result, the nozzle will heat up in the place where the measurement was last made. The essence of smart parking is to warm up the nozzle in a place close to the print, so as not to carry the hot nozzle through the print surface.

Also in your version
```
M140 S {bed_temp}
M104 S {extruder_temp}
TEMPERATURE_WAIT SENSOR = heater_bed MINIMUM = {bed_temp-2}
TEMPERATURE_WAIT SENSOR = extruder MINIMUM = {extruder_temp-4}
```
A more tolerant warm-up occurs, in which you do not need to wait for the temperature to stabilize. But in this case, we provoke the user to print with an incorrect PID, which means getting a lower-quality print. After all, if the user gets a long heating, he concludes that he needs to calibrate the PID, and in the case of a quick exit to print, he will not see this problem.

PS: The mod can be translated into Spanish ```LANG LANG=es```

**Comment by function3d** [comment]
I’ve been trying to use git directly inside the printer through SSH, but I haven’t been able to execute the git command successfully.

My goal is the following:

Be able to pull and load the latest commit from the repository in order to test it.

Keep the ability to always revert back to the original commit where I developed my own changes.

Any advice, steps, or requirements would be very helpful 🙏

**Comment by ghzserg** [comment]
Chroot /usr/data/.mod/.zmod/
Run git

**Comment by function3d** [comment]
Hi,

I am testing the last version 1.6.1-15-g3149bfa3

This error occurred after about 50 successful filament changes.  This is the second time it has happened to me, the first time was with 1.5:

```
idle_timeout: Timeout set to 1800.00 s
9:47 PM
tgalarm_photo Filament jam detected (IFS).
9:47 PM
Filament jam detected (IFS).
9:47 PM
idle_timeout: Timeout set to 86400.00 s
9:47 PM
Unknown command:"IPE_END"
9:47 PM
info Fan: 50.19607843137255
9:47 PM
info Temp: T205.0
9:47 PM
idle_timeout: Timeout set to 1800.00 s
9:47 PM
Restoring "extruder" temperature to 205.0/60.0°C Fan: 0.0
9:46 PM
info Loading filament at 220.0 for 50.0mm at 5.0 mm/s
9:46 PM
info Loading filament at 220.0 for 50.0mm at 5.0 mm/s
idle_timeout: Timeout set to 86400.00 s
9:43 PM
Разблокировка прутка ALL
9:43 PM
tgalarm_photo Ошибка при смене филамента: IFS: Вышло время для получения статуса 127
Встаю на паузу
9:43 PM
Ошибка при смене филамента: IFS: Вышло время для получения статуса 127
Встаю на паузу
9:43 PM
IFS: Вышло время для получения статуса 127
9:43 PM
IFS: Вышло время для получения статуса 127
9:43 PM
IFS: Вышло время для получения статуса 127
9:43 PM
IFS: Вышло время для получения статуса 127
9:43 PM
IFS: Вышло время для получения статуса 127
9:43 PM
Блокировка прутка 2
9:43 PM
info Go to trash
9:43 PM
info Cutting the filament
```

My procedure was:

- Heat the nozzle (the pause causes it to cool down).
- Extrude 50mm.
- It extrudes filament without any problems.
- Press resume on the guppy screen.
- The tool head go from trash to clear in the silicone and after that went diagonally and slowly to the TRASH position, which caused it to collide with the lever and the X and Y shifted.
- After that, the print continued even though the layer was shifted and immediately gave the error “Filament jam detected (IFS).”
- I  stop the print

I'm a bit lost trying to locate the exact gcode that is running when I press RESUME. Can you help me?

**Comment by function3d** [comment]
I think I've found the collision problem:

The slow, diagonal movement from the silicone to the trash position is caused by this line in client.cfg:
`RESUME_BASE VELOCITY={params.VELOCITY | default(sp_move)} `
which restores the position to TRASH and does so diagonally since the pause occurred in the TRASH position.

Before RESUME_BASE, _RESUME_MACRO is executed, which is the macro that leaves the nozzle in the silicone, and as a result, when restoring the RESUME_BASE position, it collides.

I have rewritten the _RESUME_MACRO macro in this way without _CLEAR_REZINA, and it works without colision.
```
[gcode_macro _RESUME_MACRO]
gcode:
    _GOTO_TRASH
    _ENABLE_SENSOR
    M106 S102
    G92 E0
    G1 E30 F300 #Poop
    G92 E0
    G1 E-2 F300
    G92 E0
    _SBROS_TRASH
    M106 S0
    END_CHANGE_FILAMENT RESUME=1
```
The root cause of this problem 
```
Error during filament change: IFS: Timeout for status 127
Pausing
```
has continued to occur randomly after resuming printing.

**Comment by ghzserg** [comment]
I see several errors here:
1. `Unknown command:"IPE_END"` - there is no such command in the mod.
2. Error when changing the filament: IFS: Time has expired to get status 127. To determine the cause, you need to add 
```
[zmod_ifs]
debug=True
```
to user.cfg
3. Error with RESUME. Resumes the print from a pause, first restoring the previously captured position. The VELOCITY parameter determines the speed at which the tool should return to the original captured position. If you were in the basket and paused, then after returning from pause it goes to the last point, namely, to the basket. By removing _CLEAR_REZINA, which leaves the nozzle in the rubber, you move it to the basket. I changed the recovery macro, which checks that if the last nozzle position before the pause is beyond the maximum coordinates, then y is set as the maximum coordinate (200 for 5x), and x is set as the last position. This ensures that when resuming printing there will be no impact with the lever. But if the nozzle remains in the basket during the pause, then it can only leave it in a straight line, it will hit it diagonally.
Update mod

**Comment by ghzserg** [comment]
I looked through the code and couldn't find it anywhere
status=127
I want to get TAR_CONFIG from you
https://github.com/ghzserg/zmod/wiki/FAQ_en#how-to-contact-support

**Comment by function3d** [comment]
[config.zip](https://github.com/user-attachments/files/22210205/config.zip)

**Comment by function3d** [comment]
Looking back, I managed to run a 10-hour print with zero incidents in version 1.5: 1.5.5-57. I'm going to try that version again, since now the error always appears after a few color changes.

**Comment by function3d** [comment]
There is an additional error when I try to resume then print after 127 status : `!! Unable to parse move 'G1 Y220.0 F'`
Perhaps along these lines? 128:client.cfg :  `G1 Y{client.max_y} F{params.VELOCITY}`

**Comment by ghzserg** [comment]
There is no point in checking old versions. Because the error is given by the FFS
The status of the FFS is ready for the next command, it is 5.
You get the status 127.
There are 2 options here, either this is an FFS error or it can be ignored
FFS_state: 127

**Comment by ghzserg** [comment]
Try printing the file via the native screen and if the logs also show status 127, then at least we will know what to do and what the native firmware does in this case. My IFS still doesn't work, so I can't check

**Comment by function3d** [comment]
With the native display (DISPLAY_ON) It does not print, it says

https://github.com/user-attachments/assets/2e4d1c75-c186-4d36-ac65-e190ab9149f6
https://github.com/user-attachments/assets/ffc6c63c-0856-4863-b2ba-327a56f059b5

Something strange is happening with the IFS, we will have to wait until your IFS is operational again.

```
18:28:18 
// value:0.99857
18:28:31 
// value:0.99911
18:28:35 
// value:0.99878
18:28:40 
// value:0.99881
18:28:41 
// value:0.99881
18:28:41 
// value:0.99884
18:28:41 
// value:0.99878
18:28:44 
// value:0.99878
18:28:45 
// value:0.99872
18:28:49 
// value:0.99878
18:28:50 
// value:0.99872
18:28:55 
// Unknown command:"_IFS_AUTOINSERT"
18:28:58 
// value:0.99878
18:28:59 
// value:0.99878
18:28:59 
// value:0.99878
18:29:00 
// Unknown command:"_IFS_AUTOINSERT"
18:29:00 
// Unknown command:"_IFS_AUTOINSERT"
18:29:02 
// value:0.99884
18:29:02 
// value:0.99884
18:29:02 
// value:0.99884
18:29:10 
// value:0.99875
18:29:21 
// value:0.99869
18:29:21 
// value:0.99869
18:29:49 
// value:0.99887
18:29:50 
// value:0.99878
18:29:53 
// value:0.99878
18:29:54 
// value:0.99869
18:30:28 
// value:0.99857
18:30:52 
// value:0.99866
18:30:52 
// value:0.99878
18:30:57 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:30:57 
// value:0.99887
18:30:59 
// value:0.99893
18:31:04 
// value:0.99878
18:31:05 
// value:0.99884
18:31:25 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:31:25 
// value:0.99878
18:31:27 
// value:0.99875
18:31:35 
// value:0.99857
18:31:36 
// value:0.99875
18:31:36 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:31:36 
// value:0.99899
18:31:37 
// value:0.99853
18:31:48 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:31:48 
// value:0.99869
18:31:50 
// value:0.99878
18:32:03 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:32:03 
// value:0.99860
18:32:05 
// value:0.99875
18:32:16 
// IFS: sensor error: read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
18:32:16 
// value:0.99869
18:32:18 
// value:0.99866
18:32:26 
// value:0.99863
18:32:27 
// value:0.99884
18:32:35 
// value:0.99869
18:32:36 
// value:0.99890
18:32:40 
// value:0.99899
18:32:40 
// value:0.99878
18:32:53 
// value:0.99853
18:32:54 
// value:0.99847
18:32:58 
// value:0.99857
18:32:58 
// value:0.99844
18:33:02 
// value:0.99878
18:33:03 
// value:0.99872
```

**Comment by ghzserg** [comment]
Уберите из user.cfg zmod_ifs они конфликтуют с родным экраном

**Comment by function3d** [comment]
- Tested with native screen and user.cfg and filament.json modified but I don't know to what extent they influence the native screen: **No pauses, 0 issues** 
- Tested with 1.6 update, no modifications to user.cfg and filament.json: **FFS_state: 127 pause print**
- Tested with 1.5: 1.5.5-57: **FFS_state: 127 pause print**

I think I have a semi-broken IFS, I'm going to take it apart and clean it to see if that helps.

I've also been thinking, what if in the case of 127 the pending command is retried?

**Comment by ghzserg** [comment]
On the native screen you will not have pauses. You need to print on the native screen. Then open the log file Firmwareexe.log Or send it to me. And there see if 127 is found or not.

**Comment by function3d** [comment]
In the latest tests, status 127 appeared very quickly. At first, it took much longer to occur, and as far as I can remember, it has always been in slot 2.

After disassembling the IFS, cleaning it, and blowing it out a little, I am testing directly in slots 3 and 4, and so far, there has been no 127. I'm keeping my fingers crossed.

If it is a physical problem with slot 2, then the native screen also deals with it, but somehow solves it without pauses or incidents.

I'll keep you informed. As soon as I can, I'll test the native screen again and check the Firmwareexe.log

**Comment by function3d** [comment]
Perfect printing with the latest version plus my modifications in user.cfg and filament.json with slots 3 and 4, then the same print with slots 1 and 2 failed again (127) operating with slot 2.

FFS_state: 127 found in Firmwareexe.log, there have been no pauses or messages on the screen. (slot 1?)

[firmwareExe.log](https://github.com/user-attachments/files/22244354/firmwareExe.log)

**Comment by function3d** [comment]
line  2574 (2025.09.09 22:07:45.083):

```
2025.09.09 22:07:38.236 <DEBUG> serial/SerialObject.cpp checkRefulling data:  "F13 ok. FFS_state: 26 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 2 time: 2 
2025.09.09 22:07:39.340 <DEBUG> serial/SerialObject.cpp checkRefulling data:  "F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 2 time: 3 
2025.09.09 22:07:39.344 <DEBUG> sendGcodeCmd code:  "{"id":5742,"method":"gcode/script","params":{"script":"GET_FILAMENT_VALUE"}}" 
2025.09.09 22:07:39.349 <DEBUG> serial/SerialObject.cpp value: 0.61929 
2025.09.09 22:07:39.352 <DEBUG> serial/Serial.cpp sendToUart4WaitRecv Serial: write buf :  "F24 C1" len: 6 
2025.09.09 22:07:39.557 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 0 
2025.09.09 22:07:40.661 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 1 
2025.09.09 22:07:41.766 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 00000101 qiehuan_GCONF: 00000101" chn: 1 count: 2 
2025.09.09 22:07:42.871 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 3 
2025.09.09 22:07:43.975 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 4 
2025.09.09 22:07:45.083 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 127 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 5 
2025.09.09 22:07:45.088 <DEBUG> serial/SerialObject.cpp checkCrotchCutting Drv error: 
2025.09.09 22:07:45.090 <DEBUG> serial/Serial.cpp sendToUart4WaitRecv Serial: write buf :  "F15 C" len: 5 
2025.09.09 22:07:45.193 <DEBUG> serial/Serial.cpp sendToUart4WaitRecv Serial: write buf :  "F24 C1" len: 6 
2025.09.09 22:07:46.397 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 2 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 1 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 1 
2025.09.09 22:07:47.501 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 2 
2025.09.09 22:07:48.606 <DEBUG> serial/SerialObject.cpp checkCrotchCutting data:  "F13 ok. FFS_state: 5 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 count: 3 
2025.09.09 22:07:49.610 <DEBUG> serial/Serial.cpp sendToUart4WaitRecv Serial: write buf :  "F10 C1 L1000 S1200" len: 18 
2025.09.09 22:07:49.814 <DEBUG> serial/SerialObject.cpp checkFeeding data:  "F13 ok. FFS_state: 11 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 1 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc" chn: 1 time: 0 
```

**Comment by function3d** [comment]
It seems that “F24 C1” fails "Drv error: (empty)" with status 127 and then sends “F15 C,” which I have tested and does not make any movement in the IFS under normal circumstances, it just returns “F15 ok.” and then immediately seems to retry the “F24 C1” command.

**Comment by ghzserg** [comment]
I've seen it all. But I have a day job. And I fix the behavior when I have time. Download the update. It should fix the behavior, But it needs tests

**Comment by function3d** [comment]
No worries, no rush, day job comes first. I’ll test the update

**Comment by function3d** [comment]
I think you've already fixed it in IFS_F10 and IFS_F11, but the following are also always retried three times:
IFS_F24
IFS_F23
IFS_F39
IFS_F18

**Comment by function3d** [comment]
I think this solves it.:

In the previous commands, instead of this code:

```
if ret_code==RET_RETRY:
    continue
```
use this other:
```
if ret_code!=RET_RETRY:                                                                                                                                      
    break
```
testing...

**Comment by function3d** [comment]
Something is wrong with IFS_F11

```
fluidd
Console
01:01:02 
// Don't reboot printer automatically // SAVE_ZMOD_DATA AUTO_REBOOT=0
01:01:02 
info System-wide parameters
01:01:02 
// Save data for print recovery // SAVE_ZMOD_DATA SAVE_RESTORE=1
01:01:02 
// Don't hide color selection when printing starts // SAVE_ZMOD_DATA SILENT=0
01:01:02 
// Insert rod automatically // SAVE_ZMOD_DATA AUTOINSERT=1
01:01:02 
// Use SCV from config for shaper graphs // SAVE_ZMOD_DATA FIX_SCV=1
01:01:02 
// Don't fix E0011 error // SAVE_ZMOD_DATA FIX_E0011=0
01:01:02 
// Fix E0017 error // SAVE_ZMOD_DATA FIX_E0017=1
01:01:03 
// LED brightness at power on: 50 // SAVE_ZMOD_DATA LED=50
01:01:03 
// Play MIDI at power on:  // SAVE_ZMOD_DATA MIDI_ON=
01:01:03 
// Allow Chinese clouds // SAVE_ZMOD_DATA CHINA_CLOUD=1
01:01:03 
// Use Fluidd/Mainsail button settings from ZMOD // SAVE_ZMOD_DATA SAVE_MOONRAKER=0
01:01:03 
// Turn off native screen after (sec): 30 // SAVE_ZMOD_DATA DISPLAY_OFF_TIMEOUT=30
01:01:03 
// Using native Klipper 12
01:01:03 
// Klipper process priority (1-min, 40-max): 20
01:01:03 
// Weight control is not configured. // To configure: NOZZLE_CONTROL WEIGHT=1500
01:01:03 
// Available languages: en, ru, de, fr, it, es, ja, ko, zh // LANG LANG=en
01:01:03 
// zversion:
01:01:03 
// Installed from USB: 1.6.1. Update from Fluidd/Mainsail: 1.6.1
23:25:36 
info Native screen disabled
23:25:41 
info You are NOT using native screen
23:25:41 
// Using native Klipper 12
23:25:41 
// zssh:
23:25:41 
// Installed from USB: 1.6.1. Update from Fluidd/Mainsail: 1.6.1
23:25:41 
// Zmod version: 1.6.1 Date:   Wed Sep 10 21:46:23 2025 +0500
23:25:41 
ok
23:26:09 
// zrestore:
23:26:09 
// Print recovery file not found
23:28:05 
info You are NOT using native screen
23:28:05 
// Using native Klipper 12
23:28:05 
// zssh:
23:28:05 
// Installed from USB: 1.6.1. Update from Fluidd/Mainsail: 1.6.1
00:03:10 
info Using global Z-Offset control. SKIP_ZOFFSET and Z_OFFSET parameters ignored
00:04:00 
// Smart Park coordinates: 55.89190000000001,81.678.
00:04:51 
// F24 C1 > F24 ok. chan 1.
00:04:53 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 3 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:04:54 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:04:55 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 1 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:04:57 
// F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:04:57 
// Извлечь пруток 1 длинной 92 со скоростью 1200
00:04:57 
// F11 C1 L92 S1200 > F11 ok. FFS channel 1 exiting.
00:04:57 
// Извлечь пруток 1 длинной 92 со скоростью 1200
00:04:58 
!! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
00:04:58 
!! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
00:04:58 
!! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
00:04:58 
!! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
00:04:58 
!! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
00:04:58 
!! Ошибка при смене филамента: F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
Встаю на паузу
00:04:58 
tgalarm_photo Ошибка при смене филамента: F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
Встаю на паузу
00:04:58 
// Разблокировка прутка ALL
00:04:59 
// F18 > F18 ok
00:04:59 
// F13 need:None|5 cur:2 > F13 ok. FFS_state: 2 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 5 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:00 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:02 
// F13 need:None|5 cur:12 > F13 ok. FFS_state: 12 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 1 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:03 
// F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:03 
// idle_timeout: Timeout set to 86400.00 s
00:05:06 
// idle_timeout: Timeout set to 86400.00 s
00:05:06 
// Print already paused
00:05:06 
!! Filament runout detected (Head)
00:05:06 
tgalarm_photo Filament runout detected (Head)
00:05:06 
info T0
00:05:06 
// T0
00:05:06 
info Loading filament 2 PLA
00:05:06 
info Go to trash
00:05:06 
info Heating the nozzle to 205 degrees
00:05:06 
// Блокировка прутка 2
00:05:07 
// F24 C2 > F24 ok. chan 2.
00:05:07 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:09 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:10 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 4 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:11 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:12 
// F13 need:None|5 cur:18 > F13 ok. FFS_state: 18 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:14 
// F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:14 
// Вставить пруток 2 длинной 1000 со скоростью 600
00:05:14 
// F10 C2 L1000 S600 > F10 ok. FFS channel 2 feeding.
00:05:15 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:16 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:17 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:18 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:20 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:21 
// F13 need:22|5 cur:22 > F13 ok. FFS_state: 22 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:21 
// Останавливаю движение прутка
00:05:21 
// F112 > F112 ok.
00:05:21 
!! Остановился пруток 2 в IFS
00:05:21 
!! Остановился пруток 2 в IFS
00:05:21 
!! Остановился пруток 2 в IFS
00:05:21 
!! Ошибка при смене филамента: Остановился пруток 2 в IFS
Встаю на паузу
00:05:22 
tgalarm_photo Ошибка при смене филамента: Остановился пруток 2 в IFS
Встаю на паузу
00:05:22 
// Разблокировка прутка ALL
00:05:22 
// F18 > F18 ok
00:05:23 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:24 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 4 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:25 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:26 
// F13 need:None|5 cur:12 > F13 ok. FFS_state: 12 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:28 
// F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:05:28 
// idle_timeout: Timeout set to 86400.00 s
00:05:28 
// Print already paused
00:05:30 
!! Resumption interrupted !!! "head_switch_sensor" has detected that the filament has run out, please load it and press RESUME
00:05:30 
// action:prompt_beginResumption interrupted!!!
00:05:30 
// action:prompt_text "head_switch_sensor" has detected that the filament has run out, please load it and press RESUME
00:05:30 
// action:prompt_footer_button Ok|RESPOND TYPE=command MSG=action:prompt_end|info
00:05:30 
// action:prompt_show
00:07:15 
// action:prompt_end
00:07:17 
// idle_timeout: Timeout set to 1800.00 s
00:07:21 
// Разблокировка прутка ALL
00:07:22 
// F18 > F18 ok
00:07:23 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:07:24 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:07:25 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 4 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:07:26 
// F13 need:None|5 cur:3 > F13 ok. FFS_state: 3 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:07:28 
// F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:07:28 
info Work completed
00:07:53 
info Motors disabled

```

**Comment by ghzserg** [comment]
Yes, there was a copying error. And a couple more minor errors. I corrected it and ask you to check if everything works correctly now.

**Comment by function3d** [comment]
```
// Извлечь пруток 1 длинной 92 со скоростью 1200
// F11 C1 L92 S1200 > F11 ok. FFS channel 1 exiting.
// Извлечь пруток 1 длинной 92 со скоростью 1200
!! F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
!! F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
!! F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
!! F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
!! F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
!! Ошибка при смене филамента: F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
Встаю на паузу
tgalarm_photo Ошибка при смене филамента: F11 C1 L92 S1200#14 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
Встаю на паузу
// Разблокировка прутка ALL
```

I think it is missing the `else: break` to the `if wait == 1:` in `IFS_F11`

**Comment by ghzserg** [comment]
I added a break. But I don't think it's the problem. The absence of a break would trigger the filament loading 3 times in a row. And you have an error saying that the IFS is not ready yet

**Comment by ghzserg** [comment]
```
00:04:57 // F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 1 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
00:04:57 // F11 C1 L92 S1200 > F11 ok. FFS channel 1 exiting.
00:04:58 !! F11 C1 L92 S1200#110 ret F11 ok. FFS not ready. != F11 ok. FFS channel 1 exiting.
```
As you can see from the log. IFS was ready at 00:04:5, and at 00:04:58 it already gave an error

**Comment by function3d** [comment]
IFS_F11 is called in line 876 zmod_ifs.py with `WAIT=0`, so it was definitely trying three times in a row.

**Comment by ghzserg** [comment]
In any case, all changes have already been made and testing is required.

**Comment by function3d** [comment]
A question about the next command in zmod_ifs.py:
`def cmd__IFS_REMOVE_PRUTOK(self, gcmd, prutok, force, config):`
This needs to be or can be in a gcode_macro in ad5x.cfg, for example.
I want to modify the call to IFS_F11 and try different values in LEN and SPEED, as it seems to me that the IFS is pulling the filament faster than the extruder can handle, and you can hear a clicking sound when it pulls the filament.

**Comment by function3d** [comment]
Furthermore, I believe that WAIT=0 calling IFS_F11 (I have looked it up and I believe it is the only command that is called with WAIT=0) is never retried if FFS_state: 127

**Comment by ghzserg** [comment]
Да на 127 он не отреагирует.
Т.к. после того как был вызван F11
Сразу начинает работать экструдер. 
В противном случае действия параллельно выполняться не будут.
Как вариант можно добавить команду ожидания готовности ифс.

**Comment by ghzserg** [comment]
The IFS pulls the rod at a speed twice as fast as the extruder pulls. Alternatively, the IFS speed can be taken out as a separate parameter.

**Comment by ghzserg** [comment]
I looked at the code again
Yes, it makes sense to take out _IFS_REMOVE_PRUTOK
Also added a wait, tt. the extruder starts working first, and only then the IFS works.

**Comment by function3d** [comment]
> The IFS pulls the rod at a speed twice as fast as the extruder pulls

Is this only when pulling or also when pushing?
I am testing when pushing (IFS_F10) and for the same distance, the extruder takes twice as long to stop as the IFS.

```
G1 E20 F300
IFS_F10 PRUTOK={prutok} LEN=20 SPEED=600
```
This  start  and stop (extruder and IFS) at  the same time:
```
G1 E20 F300
IFS_F10 PRUTOK={prutok} LEN=20 SPEED=300
```

**Comment by function3d** [comment]
The same goes for IFS_F11, I don't understand what you mean by:

> `The IFS pulls the rod at a speed twice as fast as the extruder pulls`

I understand that the `SPEED` parameter in the IFS is in mm/s, just like the `F` parameter in the `G1` command.

**Comment by function3d** [comment]
IFS_F10 and IFS_F11 (I would call them IFS_LOAD and IFS_UNLOAD or IFS_PUSH and IFS_PULL or something that describes what they do)

I have rewritten them in simpler terms: 

```
def cmd_IFS_F10(self, gcmd):                                                                                            
        if not self.ifs:                                                                                                    
            self.gcode.run_script_from_command("_IFS_OFF")                                                                  
            return                                                                                                          
                                                                                                                            
        prutok = gcmd.get_int('PRUTOK', 1)                                                                                  
        leng = gcmd.get_int('LEN', 90)                                                                                      
        speed = gcmd.get_int('SPEED', 1200)                                                                                 
        if speed == 0:                                                                                                      
            self.print_str("Скорость не может быть = 0", False)
        check = gcmd.get_int('CHECK', 0)                                                                                    
                                                                                                                            
        for attempt in range(RETRY_COUNT):                                                                                  
            response = self._cmd_IFS_F10(prutok, leng, speed)                                                               
            if check == 1:                                                                                                  
                success, ret_code, values = self.wait_for_state(                                                            
                    Port=prutok,                                                                                            
                    FFS_state=FFS_STATUS_ZAGRUZKA,                                                                          
                    silk={'count': 3, 'status': False},                                                                     
                    stall={'count': 3, 'status': False},                                                                    
                    extruder={'count': 1, 'status': True},                                                                  
                    timeout=120                                                                                             
                )                                                                                                           
            else:                                                                                                           
                success, ret_code, values = self.wait_for_state()                                                           
                                                                                                                            
            self.info(f"F10 > ret_code: {ret_code}")
                                                                                                                            
            if not success:                                                                                                 
                gcmd = self.gcode.create_gcode_command("IFS_F112", "IFS_F112", {})                                          
                self.cmd_IFS_F112(gcmd)                                                                                     
                                                                                                                            
            if ret_code!=RET_RETRY:                                                                                         
                break
```

```
def cmd_IFS_F11(self, gcmd):
        if not self.ifs:
            self.gcode.run_script_from_command("_IFS_OFF")
            return

        prutok = gcmd.get_int('PRUTOK', 1)
        leng = gcmd.get_int('LEN', 90)
        speed = gcmd.get_int('SPEED', 1200)
        if speed == 0:                                                                                                      
            self.print_str("Скорость не может быть = 0", False)

        for attempt in range(RETRY_COUNT):
            response = self._cmd_IFS_F11(prutok, leng, speed)
            success, ret_code, values = self.wait_for_state()
            
            if not success:                                                                                                 
                gcmd = self.gcode.create_gcode_command("IFS_F112", "IFS_F112", {})                                          
                self.cmd_IFS_F112(gcmd)                                                                                     
                                                                                                                            
            if ret_code!=RET_RETRY:                                                                                         
                break
```

I am testing them with this GCODE:

```
[gcode_macro TEST]
gcode:
    {% set prutok                          = params.PRUTOK|default(1)|int %}
    M83
    _DISABLE_SENSOR
    IFS_F24 PRUTOK={prutok} 
    IFS_F10 PRUTOK={prutok} LEN=700 SPEED=600 CHECK=1 #check sensor head
    G1 E10 F300
    # Simultaneously advance the extruder and the IFS to capture the filament with the extruder
    IFS_F10 PRUTOK={prutok} LEN=10 SPEED=300 
    IFS_F39 PRUTOK={prutok}  # IFS released filament
    G1 E10 F300 # push by extruder only, this runs after IFS_F39 has finished, which is ideal.
    G4 P3000 # wait for nothing
    IFS_F24 PRUTOK={prutok} # The IFS grips the filament
    G1 E-30 F600  #retract by extruder and pull by IFS (next command) at the same time
    IFS_F11 PRUTOK={prutok} LEN=100 SPEED=600
    IFS_F39 PRUTOK={prutok}
    _ENABLE_SENSOR
```

Extruder and IFS run simultaneously, which is the desired behavior.

Testing printing also, it works, retries in case of FSS_state: 127 should also work (waiting for the 127). As you can see, I have removed the WAIT parameter, and only in the case of IFS_F10 does it have the CHECK parameter to stop with the extruder filament sensor.

**Comment by function3d** [comment]
FFS_state: 127 occurred while printing

```
....
22:54:09 // Разблокировка прутка 2
22:54:10 // F39 C2 > F39 ok. FFS channel 2 release.
22:54:11 // F13 need:None|5 cur:23 > F13 ok. FFS_state: 23 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
22:54:12 // F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
22:54:12 // Останавливаю движение прутка
22:54:12 // F112 > F112 ok.
22:54:17 // Помечаем пруток 2
22:54:18 // F23 C2 > F23 ok. chan 2.
22:54:18 // F13 need:None|5 cur:127 > F13 ok. FFS_state: 127 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 2 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
22:54:18 // Сброс драйвера
22:54:19 // F15 > F15 ok.
22:54:20 // F23 C2 > F23 ok. chan 2.
22:54:20 // F13 need:None|5 cur:5 > F13 ok. FFS_state: 5 silk_state: 3 chan: 2 ffs_channels_insert: 0 stall_state: 0 jinsi_GCONF: 000001dc qiehuan_GCONF: 000001dc
22:54:20 // Пруток в экструдере
....
```

**Comment by ghzserg** [comment]
The task of the mod is to repeat the behavior of the native firmware and only if the user needs it, then change it.
By default, everything should work as close to the original as possible.
In the original firmware
First, F10 is executed, and only then E1
This is exactly why the WAIT parameter was introduced.
In the current version, I swapped the order of calls. But I do not plan to delete the WAIT parameter, since it may be necessary to launch F10 in non-waiting mode.
I also do not see any point in renaming it, since all commands to the IFS are named by indexes

**Comment by ghzserg** [comment]
Your version does not have the WAIT parameter. 
And in case of a driver error, F112 will be called and only then the filament loading will be restarted. There is also no output of the reason for the stop. In particular, if the rod stops, your code will simply display a message and move on. But it should stop and pause. I talked about the double speed of the IFS operation using this code
```
ad5x.cfg: IFS_F11 PRUTOK={prutok} LEN={filament_tube_length} SPEED={filament_unload_speed*2}
ad5x.cfg: IFS_F11 PRUTOK={prutok} LEN={nozzle_cleaning_length*1.67|int} SPEED={filament_unload_speed*2} #WAIT=0
```

And it is unclear why it was necessary to remove WAIT in your code if it was removed earlier in commit 996ecb2ad7b2eb61ea22f8c965d9ec5dd309680b

**Comment by function3d** [comment]
I remove WAIT because my F10 and F11 always wait. I understand that WAIT=1 means that the next command will not be executed until the movement is completed in the IFS,  and that is what happens here for example:

```
M83
IFS_F10 PRUTOK=1 LEN=50 SPEED=600 # <-- with my version of IFS_F10
G1 E50 F300 # <-- this will run when IFS finishes the 50 mm movement
```

All IFS commands should wait until they are completed. Is there any case where it is not necessary to wait, especially knowing that they can fail with FFS_state: 127?

**Comment by ghzserg** [comment]
You gave an example of when you should not wait.
We need to pull the rod from the extruder
If the first command is the IFS without waiting and the second is the extruder command, then the IFS will pull the rod, but it is clamped in the extruder.
And here the 2 options can be swapped
First, start pulling the rod from the extruder, and without waiting through M400, start pulling from the IFS
Or Start pulling from the IFS without waiting and then pull from the extruder
There is a command IFS_112 that does not require waiting.
I believe that it is the user's right to wait or not to wait. That is why all IFS commands support both modes.

**Comment by function3d** [comment]
No, man, the example is to show that my IFS_10 waits (does not need the WAIT parameter) by default, so I haven't removed it, but rather made wait the default behavior.

If you want the IFS and the extruder to move at the same time, then put G1 E50 before IFS_F10, as you mentioned you had already done.

**Comment by ghzserg** [comment]
https://github.com/ghzserg/zmod/wiki/Global_en#use_trash_on_print

**Comment by ninjamida** [comment]
I love your custom _ORIG_CLEAR_NOZZLE routine, but one issue with it: When it finishes, the print head is still at Y=228.50; if the printer then gets a _GOTO_TRASH command, it will crash into the trash chute lever and become misaligned. Additionally, all other scripts use {client.custom_park_y} instead of hardcoding 228.50.

I did wonder if you left it at Y=228.50 to reduce leakage, but I find that if we keep it there until the nozzle cools to 140, then move it back to Y=220, there's no leakage.

Here's my modified version of it that fixes both of these issues. Additionally, I made two more changes: I removed the bed heating (since it isn't necessary for this), and I removed the word "native" from the text written to console as it's not accurate. I also did some general tidyup, such as changing "M104 S{140}" to "M104 S140" (no need for the curly braces there).

```
[gcode_macro _ORIG_CLEAR_NOZZLE]
# Modification: Replaced with completely custom routine (sourced from https://github.com/ghzserg/zmod_ff5x/issues/3 first post)
# I have then further modified this custom routine, to move the nozzle back to Y=220 at the end of the routine, and eliminate the bed heating since it isn't necessary for this.
gcode:
    {% set client = printer['gcode_macro _CLIENT_VARIABLE'] | default({}) %}
    {% set extruder_temp = params.EXTRUDER_TEMP|default(230)|float %}
    {% set bed_temp = params.BED_TEMP|default(80)|float %}
    {% set ignore_temp = params.IGNORE_TEMP|default(0)|int %}
    {% set preclear = params.PRECLEAR|default(0)|int %}

    {% if ignore_temp == 0%}
        RESPOND PREFIX="info" MSG="Running nozzle cleaning {extruder_temp}/{bed_temp}"
    {% else %}
        RESPOND PREFIX="info" MSG="Nozzle pre-cleaning"
    {% endif %}

    _G28
    G1 Z5 F600
    _GOTO_TRASH    
    M104 S{extruder_temp} T0
    TEMPERATURE_WAIT SENSOR=extruder MINIMUM={extruder_temp}
    M104 S140
    M106 S102
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E-3 F300
    G92 E0
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={180}
    _SBROS_TRASH
    _CLEAR_REZINA
    G1 Y{client.custom_park_y} F3000
    M106 S{255/100*80}
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={142}
    M106 S0
    G1 Y220 F3000
    M400
```

This is probably not a candidate for inclusion in the mod itself, but could be useful for people customizing their printer's behavior.

**Comment by function3d** [comment]
@ninjamida 
I have added some of your changes, but I have kept the bed heating because it is a job that is done in advance to reduce waiting times. I also had some comments that clarify my motives.
```
[gcode_macro _ORIG_CLEAR_NOZZLE] 
# 0 confidence in _CLEAR_BOARD, I don't like it rubbing against the bed to clean the nozzle.
#Also, the tool head collides with the bed handle when it is turned to the other side.
# so we poop into trash at the same time we cool down the nozzle, wait for 180ºC and _SBROS_TRASH 
# and them CLEAR_REZINA and wait for 140ºC in the silicone to prevent leaks
gcode:
    {% set extruder_temp = params.EXTRUDER_TEMP|default(240)|float %}
    {% set bed_temp = params.BED_TEMP|default(80)|float %}
    {% set ignore_temp = params.IGNORE_TEMP|default(0)|int %}
    {% set preclear = params.PRECLEAR|default(0)|int %}

    {% if ignore_temp == 0%}
        RESPOND PREFIX="info" MSG="Running nozzle cleaning {extruder_temp}/{bed_temp}"
    {% else %}
        RESPOND PREFIX="info" MSG="Nozzle pre-cleaning"
    {% endif %}

    _G28
    G1 Z5 F600
    _GOTO_TRASH
    M140 S{bed_temp}        
    M104 S{extruder_temp} T0
    TEMPERATURE_WAIT SENSOR=extruder MINIMUM={extruder_temp}
    M104 S140
    M106 S102
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E25 F150
    G92 E0
    G1 E-3 F300
    G92 E0
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={180}
    _SBROS_TRASH
    _CLEAR_REZINA
    M106 S{255/100*80}
    TEMPERATURE_WAIT SENSOR=extruder MAXIMUM={142}
    M106 S0
    G1 Y220 F3000
    M400
```

**Comment by function3d** [comment]
Hi,

I finally made a mod based on your mod, I hope you don't mind.

My changes to zmod_ifs.py, zmod_ifs_motion_sensor.py, and zmod_ifs_switch_sensor.py are compatible with your mod and do not alter it, but they allow me to control all presence and motion sensors individually.

The changes in user.cfg are extensive, and I replace very relevant macros from your mod.

I improve the zrestore routine with a bash script instead of a binary.

And dozens of other improvements.

https://github.com/function3d/bambufy

**Comment by ghzserg** [comment]
A lot of work has been done. Would you like to somehow pull this functionality into the main branch?

**Comment by function3d** [comment]
I see it as very complicated; it was very difficult for me to integrate it into the main branch, which is why I did it this way.

The best I can think of right now is a pull request for my changes in zmod_ifs_motion_sensor.py and zmod_ifs_switch_sensor.py, which should be compatible with zmod, and the rest in an on/off macro that [install](https://github.com/function3d/zmod_ff5x/blob/1.6/update.sh) or uninstall my changes in user.cfg, restore_gcode.sh, mainsail multicolor, etc.

What do you think?

**Comment by ghzserg** [comment]
My idea is to make it so that to expand the functionality it is enough to user.cfg.
I saw you move some of the functionality from the sensor code to other modules. I think it can be seamlessly integrated into the main code.I'll post the data recovery code, because it's the same for both the 5M and 5X. And the 5M's memory is heavy. 
I also think the multicolor mainsail will be useful to everyone. But I haven't looked at what's changed there. 
The ideal option is when you can make your modification work completely through user.cfg.
And all other changes were integrated into the general branch.This will avoid compatibility issues in the future.

**Comment by ghzserg** [comment]
I posted https://github.com/ghzserg/restore_gcode
It doesn't use tmp/printer because it has message length limits, and large object exclusions cause the Klipper to crash.
https://github.com/ghzserg/zmod/issues/194
https://github.com/ghzserg/zmod/issues/181
The ZEXCLUDE macro is used to exclude objects.
You also have a simultaneous return on XYZ, which will cause a crash if the nozzle was in the basket when the print stopped.
Therefore, I suggest using a common print recovery code. Otherwise, you'll have to track exactly what changed during recovery and why it's important.
If your recovery code requires calling any macros or code, you can add it to the main project.

**Comment by function3d** [comment]
My restore_gcode.sh has not been tested with exclude_object. I now see the potential issue. in my restore_gcode.sh I check the list of excluded objects and simply exclude them again. I understand that this will have no effect since the lines of the gcode file where the objects are defined are not executed because the entire beginning of the file is skipped to continue where it left off, and I understand from what you are saying that sending the list of objects defined by /tmp/printer is likely to reach the message limit. I will see if I can simply send each definition in different messages

**Comment by function3d** [comment]
Okay, the definition of an object can be very long and can also reach the message limit, so your ZEXCLUDE should solve the problem.

**Comment by function3d** [comment]
Why not create a new restore file with the object definitions intact at the beginning, followed by the gcode from the restore position, and send that file to print?

**Comment by ghzserg** [comment]
You can do this, but then a different file will be printed, meaning a different print history entry and a different icon, if there even is one. And why create a new file if you can simply move the pointer in the existing file?
Plus, the problem remains if objects have already been excluded. You must run EXCLUDE_OBJECT_START before you start printing.
In any case, there's already working and tested code.
